/*
* generated by Xtext
*/
package com.github.nanothor.lifetc3.ide;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LifeTC3StandaloneSetup extends LifeTC3StandaloneSetupGenerated{

	public static void doSetup() {
		new LifeTC3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

