/*
 * generated by Xtext
 */
package com.github.nanothor.lifetc3.ide;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LifeTC3RuntimeModule extends com.github.nanothor.lifetc3.ide.AbstractLifeTC3RuntimeModule {

}
