/*
 * generated by Xtext
 */
package com.github.nanothor.lifetc3.ide.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.github.nanothor.lifetc3.ide.ui.internal.LifeTC3Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LifeTC3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LifeTC3Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LifeTC3Activator.getInstance().getInjector(LifeTC3Activator.COM_GITHUB_NANOTHOR_LIFETC3_IDE_LIFETC3);
	}
	
}
