/*
 * generated by Xtext
 */
package com.github.nanothor.lifetc3.ide.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLifeTC3Validator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.github.nanothor.lifetc3.ide.lifeTC3.LifeTC3Package.eINSTANCE);
		return result;
	}
}
