/**
 * generated by Xtext
 */
package com.github.nanothor.lifetc3.ide.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class LifeTC3QuickfixProvider extends DefaultQuickfixProvider {
}
