/*
* generated by Xtext
*/
package com.github.nanothor.lifetc3.ide.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.github.nanothor.lifetc3.ide.services.LifeTC3GrammarAccess;

public class LifeTC3Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LifeTC3GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.github.nanothor.lifetc3.ide.parser.antlr.internal.InternalLifeTC3Parser createParser(XtextTokenStream stream) {
		return new com.github.nanothor.lifetc3.ide.parser.antlr.internal.InternalLifeTC3Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Prog";
	}
	
	public LifeTC3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LifeTC3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
