/*
* generated by Xtext
*/
package com.github.nanothor.lifetc3.ide.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LifeTC3AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/github/nanothor/lifetc3/ide/parser/antlr/internal/InternalLifeTC3.tokens");
	}
}
