/*
 * generated by Xtext
 */
package com.github.nanothor.lifetc3.ide.ui.contentassist

import com.github.nanothor.lifetc3.ide.ui.contentassist.AbstractLifeTC3ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LifeTC3ProposalProvider extends AbstractLifeTC3ProposalProvider {
}
