/*
 * generated by Xtext
 */
package com.github.nanothor.lifetc3.ide.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LifeTC3UiModule extends com.github.nanothor.lifetc3.ide.ui.AbstractLifeTC3UiModule {
	public LifeTC3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
